index:
    path: /
    controller: App\Controller\TableController::index

update:
    path: /update/{league}
    defaults: { _controller: 'App\Controller\TableController::update' }

league:
    path: /league/{league}
    defaults: { _controller: 'App\Controller\TableController::league' }